//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysForBoys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bestelling()
        {
            this.BestelDetails = new HashSet<BestelDetail>();
        }
    
        public int ID { get; set; }
        public System.DateTime BestelDatum { get; set; }
        public Nullable<System.DateTime> LeverDatum { get; set; }
        public Nullable<System.DateTime> VerzendDatum { get; set; }
        public string Opmerkingen { get; set; }
        public int KlantID { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BestelDetail> BestelDetails { get; set; }
        public virtual Klant Klant { get; set; }
    }
}
