//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysForBoys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.BestelDetails = new HashSet<BestelDetail>();
        }
    
        public int ID { get; set; }
        public string Naam { get; set; }
        public string Schaal { get; set; }
        public string Omschrijving { get; set; }
        public int OpVoorraad { get; set; }
        public int Besteld { get; set; }
        public decimal Prijs { get; set; }
        public int CategorieID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BestelDetail> BestelDetails { get; set; }
        public virtual ProductCategorie ProductCategorie { get; set; }
    }
}
