//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysForBoys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webshopEntities : DbContext
    {
        public webshopEntities()
            : base("name=webshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BestelDetail> BestelDetails { get; set; }
        public virtual DbSet<Bestelling> Bestellingen { get; set; }
        public virtual DbSet<Klant> Klanten { get; set; }
        public virtual DbSet<Land> Landen { get; set; }
        public virtual DbSet<ProductCategorie> ProductCategories { get; set; }
        public virtual DbSet<Product> Producten { get; set; }
    }
}
