//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysForBoys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klant()
        {
            this.Bestellingen = new HashSet<Bestelling>();
        }
    
        public int ID { get; set; }
        public string Naam { get; set; }
        public string Straat { get; set; }
        public string Postcode { get; set; }
        public string Gemeente { get; set; }
        public string Provincie { get; set; }
        public int LandID { get; set; }
        public int Userlevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelling> Bestellingen { get; set; }
        public virtual Land Land { get; set; }
    }
}
